python_django_marketplace/app_cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_shop_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_shop_id>/', views.cart_remove, name='cart_remove'),
    path('change/<int:product_shop_id>/<str:type>', views.cart_change_quantity, name='cart_change'),
]

python_django_marketplace/django_marketplace/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chaining/', include('smart_selects.urls')),
    path('i18n', include('django.conf.urls.i18n')),
    path('', include('app_shops.urls')),
    path('profile/', include('app_users.urls')),
    path('cart/', include('app_cart.urls')),
    path('order/', include('app_orders.urls')),
]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

python_django_marketplace/app_orders/models.py
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from djmoney.models.fields import MoneyField
from phonenumber_field.modelfields import PhoneNumberField

from app_shops.models.shop import ProductShop


class Order(models.Model):
    """
    Модель заказа
    """

    ORDER_STATUS = (
        ('p', _('Paid')),
        ('np', _('Not paid')),
        ('d', _('Delivery type'))
    )

    buyer = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='orders',
                              verbose_name=_('buyer'))
    comment = models.TextField(max_length=500, null=True, blank=True, verbose_name=_('comment'))
    delivery_category = models.ForeignKey('DeliveryCategory', on_delete=models.PROTECT, related_name='items',
                                          verbose_name=_('delivery category'))
    name = models.CharField(max_length=100, verbose_name=_('name'))
    phone = PhoneNumberField(verbose_name=_('phone'))
    email = models.EmailField(verbose_name=_('email'))
    city = models.CharField(max_length=100, verbose_name=_('city'))
    address = models.TextField(max_length=256, verbose_name=_('address'))
    is_free_delivery = models.BooleanField(default=False, verbose_name=_('is free delivery'))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_('created'))
    updated = models.DateTimeField(auto_now=True, verbose_name=_('updated'))
    is_canceled = models.BooleanField(default=False, verbose_name=_('is canceled'))
    status = models.CharField(default='np', choices=ORDER_STATUS, max_length=2, verbose_name=_('order status'))

    def __str__(self):
        order = _('order')
        return f'{order.capitalize()} №{self.id}'

    class Meta:
        verbose_name_plural = _('orders')
        verbose_name = _('order')

    def get_absolute_url(self) -> str:
        return reverse('order_detail', kwargs={'pk': self.pk})


class OrderItem(models.Model):
    """
    Объект заказа
    """
    order = models.ForeignKey('Order', on_delete=models.CASCADE, related_name='items', verbose_name=_('order'))
    product_shop = models.ForeignKey(ProductShop, on_delete=models.PROTECT, related_name='in_orders',
                                     verbose_name=_('product'))
    price_on_add_moment = MoneyField(max_digits=8, decimal_places=2, default_currency='RUB',
                                     verbose_name=_('price on add moment'))
    quantity = models.PositiveIntegerField(default=1, verbose_name=_('quantity'))

    class Meta:
        verbose_name_plural = _('order items')
        verbose_name = _('order item')


class PaymentItem(models.Model):
    """
    Экземпляр оплаты
    """

    PAYMENT_CATEGORY = (
        ('bank-card', _('Bank card')),
        ('some-one', _('Some other way')),
    )

    IS_PASSED_CHOICES = (
        (True, _('Passed')),
        (False, _('Payment failed'))
    )

    order = models.OneToOneField(
        'Order', on_delete=models.CASCADE, related_name='payment_item', verbose_name=_('order'))
    payment_category = models.CharField(max_length=15, choices=PAYMENT_CATEGORY, verbose_name=_('category'))
    total_price = MoneyField(max_digits=10, null=True, decimal_places=2,
                             default_currency='RUB', verbose_name=_('total price'))
    from_account = models.CharField(max_length=50, null=True, blank=True, verbose_name=_('from account'))
    is_passed = models.BooleanField(default=False, choices=IS_PASSED_CHOICES, verbose_name=_('is passed'))

    class Meta:
        verbose_name_plural = _('payment items')
        verbose_name = _('payment item')


class DeliveryCategory(models.Model):
    """
    Модель способа доставки
    """
    name = models.CharField(max_length=50, verbose_name=_('name'))
    is_active = models.BooleanField(default=False, verbose_name=_('is active'))
    price = MoneyField(max_digits=8, decimal_places=2, default_currency='RUB', verbose_name=_('price'))
    codename = AutoSlugField(max_length=100, unique=True, populate_from='name_en', verbose_name=_('codename'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = _('delivery categories')
        verbose_name = _('delivery category')

python_django_marketplace/app_shops/models/discount.py
import datetime

from autoslug import AutoSlugField
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from djmoney.models.fields import MoneyField
from imagekit.models import ProcessedImageField, ImageSpecField


def get_discount_img_path(instance, name) -> str:
    """Возвращает путь для хранения изображений данной скидки"""
    return f'img/content/discounts/{instance.discount.slug}/{name}'


class Discount(models.Model):
    """
    Модель скидки на товары
    """
    name = models.CharField(max_length=100, verbose_name=_('title'))
    description_short = models.CharField(max_length=100, verbose_name=_('description short'))
    description_long = models.TextField(verbose_name=_('description long'))
    slug = AutoSlugField(max_length=70, unique=True, populate_from='name_en', verbose_name='URL')
    shop = models.ForeignKey('Shop', on_delete=models.CASCADE, related_name='discounts',
                             verbose_name=_('shop'))
    discount_amount = MoneyField(max_digits=8, decimal_places=2, null=True, blank=True,
                                 default_currency='RUB', verbose_name=_('discount value'))
    discount_percentage = models.PositiveSmallIntegerField(null=True, blank=True,
        validators=[MaxValueValidator(99)], verbose_name=_('discount percentage'))
    min_cost = MoneyField(max_digits=8, decimal_places=2, null=True, blank=True,
                          default_currency='RUB', verbose_name=_('minimum cost'))
    date_start = models.DateTimeField(db_index=True, verbose_name=_('date start'))
    date_end = models.DateTimeField(null=True, blank=True, verbose_name=_('date end'))
    is_active = models.BooleanField(default=True, verbose_name=_('is active'))
    main_image = models.OneToOneField('DiscountImage', related_name='main_for_discount', on_delete=models.SET_NULL,
                                      null=True, blank=True, verbose_name=_('main image'))

    def __str__(self) -> str:
        return f'{self.name}'

    class Meta:
        verbose_name_plural = _('discounts')
        verbose_name = _('discount')
        ordering = ['-date_start']

    def clean(self):
        if not self.discount_amount and not self.discount_percentage or \
                self.discount_amount and self.discount_percentage:
            raise ValidationError(
                _('"discount value" and "discount percentage" fields cannot be used at the same time'))

        if not self.pk and self.date_start < timezone.now():
            raise ValidationError({'date_start': _('Date cannot be in the past')})
        elif self.pk:
            old_date_start = Discount.objects.get(pk=self.pk).date_start
            if self.date_start != old_date_start and self.date_start < timezone.now():
                raise ValidationError({'date_start': _('Date cannot be in the past')})

        if self.date_end and self.date_end < self.date_start:
            raise ValidationError({'date_end': _('Date end cannot be before date start')})

    def get_absolute_url(self) -> str:
        return reverse('discount', kwargs={'promo_slug': self.slug})

    @property
    def day_start(self) -> str:
        return datetime.date.strftime(self.date_start, '%d')

    @property
    def month_start(self) -> str:
        return datetime.date.strftime(self.date_start, '%b')

    @property
    def day_end(self) -> str:
        return datetime.date.strftime(self.date_end, '%d') if self.date_end else None

    @property
    def month_end(self) -> str:
        return datetime.date.strftime(self.date_end, '%b') if self.date_end else None


class DiscountImage(models.Model):
    """
    Модель изображения для скидки
    """
    image = ProcessedImageField(upload_to=get_discount_img_path, options={'quality': 80}, verbose_name=_('image'))
    small = ImageSpecField(source='image', id='app_shops:thumbnail_200x200')
    middle = ImageSpecField(source='image', id='app_shops:thumbnail_500x500')
    large = ImageSpecField(source='image', id='app_shops:thumbnail_800x800')
    discount = models.ForeignKey(
        Discount, on_delete=models.CASCADE, related_name='images', verbose_name=_('discount'))
    uploaded = models.DateTimeField(auto_now_add=True, verbose_name=_('uploaded'))

    def __str__(self) -> str:
        return f'Image of discount: {self.discount.name}'

    class Meta:
        verbose_name_plural = _('discount images')
        verbose_name = _('discount image')

python_django_marketplace/app_shops/models/product.py
from __future__ import annotations

from autoslug import AutoSlugField
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from imagekit.models import ProcessedImageField, ImageSpecField
from smart_selects.db_fields import ChainedManyToManyField

from app_users.models import Profile


def get_good_img_path(instance, name) -> str:
    """Возвращает путь для хранения изображений данного товара"""
    return f'img/content/products/{instance.product.slug}/{name}'


class TagProduct(models.Model):
    """
    Модель для группировки товаров по тегу
    """
    codename = AutoSlugField(max_length=100, unique=True, populate_from='name_en', verbose_name=_('codename'))
    name = models.CharField(max_length=100, verbose_name=_('name'))
    goods = models.ManyToManyField('Product', related_name='tags', blank=True, verbose_name=_('goods'))

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name_plural = _('tags')
        verbose_name = _('tag')


class FeatureName(models.Model):
    """
    Модель имени характеристики для товаров
    """
    name = models.CharField(max_length=100, verbose_name=_('name'))

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name_plural = _('features')
        verbose_name = _('feature')


class FeatureValue(models.Model):
    """
    Модель значений для имени характеристики
    """
    name = models.ForeignKey(FeatureName, on_delete=models.CASCADE,
                             related_name='feature_value', verbose_name=_('name'))
    value = models.CharField(max_length=100, verbose_name=_('value'))

    def __str__(self) -> str:
        return self.value

    class Meta:
        ordering = ['value']


class FeatureToProduct(models.Model):
    """
    Модель связывающая характеристики с товаром
    """
    product = models.ForeignKey('Product', on_delete=models.CASCADE,
                                related_name='features', verbose_name=_('product'))
    feature_name = models.ForeignKey('FeatureName', on_delete=models.CASCADE,
                                     related_name='to_shops', verbose_name=_('feature name'))
    values = ChainedManyToManyField(FeatureValue,
                                    chained_field='feature_name',
                                    chained_model_field='name',
                                    blank=True,
                                    related_name='to_shops',
                                    verbose_name=_('values'))

    class Meta:
        unique_together = ('product', 'feature_name')


class Product(models.Model):
    """
    Модель товара
    """
    name = models.CharField(max_length=120, verbose_name=_('name'))
    slug = AutoSlugField(max_length=70, unique=True, populate_from='name_en', verbose_name='URL')
    description_short = models.TextField(max_length=100, verbose_name=_('description short'))
    description_long = models.TextField(verbose_name=_('description long'))
    category = models.ForeignKey('Category', on_delete=models.CASCADE,
                                 related_name='products', verbose_name=_('products'))
    sellers = models.ManyToManyField('Shop', through='ProductShop', verbose_name=_('sellers'))
    is_active = models.BooleanField(default=False, verbose_name=_('is active'))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_('created'))
    updated = models.DateTimeField(auto_now=True, verbose_name=_('updated'))
    main_image = models.OneToOneField('ProductImage', on_delete=models.SET_NULL, null=True, blank=True,
                                      related_name='main_for_product', verbose_name=_('main image'))

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name_plural = _('products')
        verbose_name = _('product')

    def get_absolute_url(self) -> str:
        return reverse('product-detail', kwargs={'product_slug': self.slug})


class ProductImage(models.Model):
    """
    Модель изображения для товара
    """
    image = ProcessedImageField(upload_to=get_good_img_path, options={'quality': 80}, verbose_name=_('image'))
    small = ImageSpecField(source='image', id='app_shops:thumbnail_200x200')
    middle = ImageSpecField(source='image', id='app_shops:thumbnail_500x500')
    large = ImageSpecField(source='image', id='app_shops:thumbnail_800x800')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images', verbose_name=_('product'))
    uploaded = models.DateTimeField(auto_now_add=True, verbose_name=_('uploaded'))

    def __str__(self) -> str:
        return f'Image of product: {self.product.name}'

    class Meta:
        verbose_name_plural = _('product images')
        verbose_name = _('product image')


class Review(models.Model):
    """
    Модель отзывов
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews', verbose_name=_('product'))
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='reviews', verbose_name=_('user'))
    text = models.TextField(verbose_name=_('review text'))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_('created'))
    is_active = models.BooleanField(default=True, verbose_name=_('is active'))

    def __str__(self):
        return f'{self.profile} - {self.product}: {self.short_text()}'

    def short_text(self):
        return self.text[:30]

    short_text.short_description = 'text_short'


class ViewHistory(models.Model):
    """
    Модель истории просмотров
    """
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='history', verbose_name=_('profile'))
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='history', verbose_name=_('user'))
    date_viewed = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.id} - {self.date_viewed}'

python_django_marketplace/templates/pages/account.html
{% extends 'layout.html' %}
{% load static i18n %}


{% block page_content %}
  <div class="Middle Middle_top">
    <div class="Section Section_column Section_columnLeft">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">{% trans 'Navigation' %}</strong>
            </header>
            <div class="Section-columnContent">
              <div class="NavigateProfile">
                <ul class="menu menu_vt">
                  <li class="menu-item_ACTIVE menu-item">
                    <a class="menu-link" href="{% url 'account' %}">{% trans 'Personal account' %}</a>
                  </li>
                  <li class="menu-item">
                    <a class="menu-link" href="{% url 'edit' %}">{% trans 'Profile' %}</a>
                  </li>
                  <li class="menu-item">
                    <a class="menu-link" href="{% url 'orders' %}">{% trans 'Orders history' %}</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <div class="Account">
            <div class="Account-group">
              <div class="Account-column">
                <div class="Account-avatar">
                  {% with default_image='/static/img/icons/profile.png' %}
                    <img src="{{ image.url|default:default_image }}">
                  {% endwith %}
                </div>
              </div>
              <div class="Account-column">
                {% if object.name %}
                  <div class="Account-name">{{ object.name }}</div>
                {% else %}
                  <div class="Account-name">{{ object.user.username }}</div>
                {% endif %}
                <a class="Account-editLink" href="{% url 'edit' %}">{% trans 'Edit profile' %}</a>
              </div>
            </div>
              {% if order %}
              <div class="Account-group">
                <div class="Account-column Account-column_full">
                  <div class="Order Order_anons">
                    <div class="Order-personal">
                      <div class="row">
                        <div class="row-block"><a class="Order-title" href="{{ order.get_absolute_url }}">{% trans 'Order' %}&#32;<span
                          class="Order-numberOrder">№{{ order.id }}</span>&#32;от&#32;<span
                          class="Order-dateOrder">{{ order.created }}</span></a>
                          <div class="Account-editLink"><a href="{% url 'orders' %}">{% trans 'Orders history' %}</a>
                          </div>
                        </div>
                        <div class="row-block">
                          <div class="Order-info Order-info_delivery">
                            <div class="Order-infoType">{% trans 'Delivery type:' %}:
                            </div>
                            <div class="Order-infoContent">{{ order.delivery_category.name }}
                            </div>
                          </div>
                          <div class="Order-info Order-info_pay">
                            <div class="Order-infoType">{% trans 'Payment:' %}:
                            </div>
                            <div class="Order-infoContent">{{ order.payment_item.get_payment_category_display }}
                            </div>
                          </div>
                          <div class="Order-info">
                            <div class="Order-infoType">{% trans 'Total price' %}:
                            </div>
                            <div class="Order-infoContent">{{ order.payment_item.total_price }}
                            </div>
                          </div>
                          <div class="Order-info Order-info_status">
                            <div class="Order-infoType">{% trans 'Status:' %}:
                            </div>
                            <div class="Order-infoContent">{{ order.payment_item.get_is_passed_display }}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            {% endif %}
          {% if products %}
            {% for product in products %}
              <div class="Account-group">
                  <div class="Account-column Account-column_full">
                    <div class="Order Order_anons">
                      <div class="Order-personal">
                        <div class="row">
                          <div class="row-block"><a class="Order-title" href="/product/{{ product.slug }}">{{ product.name }}</a></div>
                          <div class="row-block">
                            <img src="{{ product.main_image.small.url }}" alt="image">
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
              {% endfor %}
          {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

python_django_marketplace/templates/pages/cart.html
{% extends 'layout.html' %}
{% load static custom_filters %}


{% block page_content %}
  <div class="Middle Middle_top">
    <div class="Section">
      <div class="wrap">
        {% if cart|length >= 1 %}
          <form class="form Cart" action="#" method="post">
            {% for item in cart %}
              {% with product=item.product.product %}
                <div class="Cart-product">
                  <div class="Cart-block Cart-block_row">
                    <div class="Cart-block Cart-block_pict">
                      <a class="Cart-pict" href="{% url 'product-detail' product.slug %}">
                        <img class="Cart-img" src="{{ product.main_image.small.url }}" alt="card.jpg"/>
                      </a>
                    </div>
                    <div class="Cart-block Cart-block_info">
                      <a class="Cart-title" href="{% url 'product-detail' product.slug %}">{{ product.name }}</a>
                      <div class="Cart-desc">
                        {{ product.description_short }}
                      </div>
                    </div>
                    <div class="Cart-block Cart-block_price">
                      <div class="Cart-price">{{ item.price|localize:request.LANGUAGE_CODE }}</div>
                    </div>
                  </div>
                  <div class="Cart-block Cart-block_row">
                    <div class="Cart-block Cart-block_seller"></div>
                    <div class="Cart-block Cart-block_amount">
                      <div class="Cart-amount">
                        <div class="Amount">
                          <a class="Amount-remove" href="{% url 'cart_change' item.product.id 'minus' %}"></a>
                          <input class="Amount-input form-input" name="amount" type="text" value="{{ item.quantity }}"
                                 readonly/>
                          <a class="Amount-add" href="{% url 'cart_change' item.product.id 'plus' %}">
                          </a>
                        </div>
                      </div>
                    </div>
                    <div class="Cart-block Cart-block_delete">
                      <a class="Cart-delete" href="{% url 'cart_remove' item.product.id %}">
                        <img src="{% static 'img/icons/card/delete.svg' %}" alt="delete.svg"/>
                      </a>
                    </div>
                  </div>
                </div>
              {% endwith %}
            {% endfor %}
          </form>

          <div class="Cart-total">
            <div class="Cart-block Cart-block_total">
              <strong class="Cart-title">Итого:</strong>
              <span class="Cart-price">{{ cart.get_total_price }}</span>
            </div>
            <div class="Cart-block">
              <a class="btn btn_success btn_lg" href="{% url 'order' %}">Оформить заказ</a>
            </div>
          </div>
        {% else %}
          <div class="cart-empty">
            <h2>Товаров нет</h2>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

python_django_marketplace/templates/pages/historyorder.html
{% extends 'layout.html' %}
{% load static i18n %}


{% block page_content %}
  <div class="Middle Middle_top">
    <div class="Section Section_column Section_columnLeft">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">{% trans 'Navigation' %}</strong>
            </header>
            <div class="Section-columnContent">
              <div class="NavigateProfile">
                <ul class="menu menu_vt">
                  <li class="menu-item">
                    <a class="menu-link" href="{% url 'account' %}">{% trans 'Personal account' %}</a>
                  </li>
                  <li class="menu-item">
                    <a class="menu-link" href="{% url 'edit' %}">{% trans 'Profile' %}</a>
                  </li>
                  <li class="menu-item_ACTIVE menu-item">
                    <a class="menu-link" href="{% url 'orders' %}">{% trans 'Orders history' %}</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <div class="Orders">
            {% for order in order_list %}
              <div class="Order Order_anons">
                <div class="Order-personal">
                  <div class="row">
                    <div class="row-block">
                      <a class="Order-title" href="{{ order.get_absolute_url }}">{% trans 'Order' %}&#32;
                        <span class="Order-numberOrder">№{{ order.id }}</span>
                        &#32;{% trans 'from' %}&#32;
                        <span class="Order-dateOrder">{{ order.created }}</span>
                      </a>
                    </div>
                    <div class="row-block">
                      <div class="Order-info Order-info_delivery">
                        <div class="Order-infoType">{% trans 'Delivery type' %}:</div>
                        <div class="Order-infoContent">{{ order.delivery_category.name }}</div>
                      </div>
                      <div class="Order-info Order-info_pay">
                        <div class="Order-infoType">{% trans 'Payment' %}:</div>
                        <div class="Order-infoContent">{{ order.payment_item.get_payment_category_display }}</div>
                      </div>
                      <div class="Order-info">
                        <div class="Order-infoType">{% trans 'Total price' %}:</div>
                        <div class="Order-infoContent">
                          <span class="Order-price">{{ order.payment_item.total_price }}</span>
                        </div>
                      </div>
                      <div class="Order-info Order-info_status">
                        <div class="Order-infoType">{% trans 'Status' %}:</div>
                        <div class="Order-infoContent">{{ order.get_status_display }}</div>
                      </div>
                      {% if not order.payment_item.is_passed %}
                        <div class="Order-info Order-info_error">
                          <div class="Order-infoType">{% trans 'Payment failed' %}:</div>
                          <div class="Order-infoContent">{{ order.payment_item.get_is_passed_display }}</div>
                        </div>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

python_django_marketplace/templates/pages/password.html
{% extends 'layout.html' %}
{% load static %}


{% block header %}
  {% include 'components/header.html' with no_bottom=True %}
{% endblock %}

{% block page_content %}
  <div class="wrapper">
  <div class="header">
    <h3 class="sign-in">Восстановление пароля (2/2)</h3>
    <h5>Придумайте новый пароль для учетной записи</h5>
  </div>

  <form method="post">
    {% csrf_token %}
    <div>
      {{ form.password }}
    </div>
    <div>
      <input type="submit" value="Сохранить пароль"/>
    </div>
  </form>
</div>
{% endblock %}

python_django_marketplace/templates/pages/payment.html
{% extends 'layout.html' %}
{% load static i18n custom_filters %}


{% block page_content %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">{% trans 'Payment' %}</h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item">
              <a href="{% url 'home' %}">{% trans 'Home' %}</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current">
              <span>{% trans 'Payment' %}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section">
      <div class="wrap">
        <div>{% trans 'Amount payable' %}:
          {{ total_price|localize:request.LANGUAGE_CODE }}
        </div>
        <form class="form Payment" method="post">
          {% csrf_token %}
          <div class="Payment-card">
            <div class="form-group">
              <label class="form-label">{% trans 'Account number' %}
                <input class="form-input Payment-bill" id="numero1" name="account_number" type="text" placeholder="9999 9999"
                       data-mask="9999 9999" data-validate="require pay"/>
              </label>
            </div>
          </div>
          <div class="Payment-pay">
            <button type="submit" class="btn btn_primary">{% trans 'Pay' %}</button>
          </div>
        </form>
      </div>
    </div>
</div>
{% endblock %}